#pragma once

#define LENGHT_OF_POST_HEAD 50
#define LENGHT_OF_POST_BODY 500
#define NUMBER_OF_TAGS 30
#define TAGS_LENGHT 10
#define NUMBER_OF_COMMENTS 50
#define COMMENT_LENGHT 250
#define NUMBER_OF_SCORES 300
#define CAPACITY_OF_POSTS 50
