name: GitHub Actions Demo
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  make check
  build:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      run: |
        pwd
        cd project
        mkdir build
        cd build
        pwd


