name: GitHub Actions Demo
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  make check
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cmake
        run: sudo apt-get install cmake
      - name: Install GTest
        run: sudo apt-get install libgtest-dev
      - name: create cmake files
        working-directory: ./project
        run:  cmake CMakeLists.txt
      - name: make cmake files
        working-directory: ./project
        run: make
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Install cmake
        run: sudo apt-get install cmake
      - name: Install GTest
        run: sudo apt-get install libgtest-dev
      - name: create cmake files
        run:  cmake CMakeLists.txt
      - run: make
      - name: check tests
        run: ./tests/test_matrix 