name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  ls
      - run:  mkdir build
      - run:  ls
      - run:  cd build
      - run:  ls