name: GitHub Actions Demo
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  make check
  build:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -la
      - working-directory: ./project/
      - run: pwd
      - run:  mkdir build 
      - working-directory: ./build/
      - run: pwd
      - run:  cmake ..
      - run:  cmake --build .


